- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10HR
    TRAINER: Siva
  tasks:
  - name: print course information
    vars:
      COURSE: DEVOPS 
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  - name: print course information again
    
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"